-- metadata
COMMENT ON TABLE supply.lfu_chpplant_prignitz IS '{
    "title": "Betriebene Blockheizkraftwerke und Verbrennungsmotoranlagen im Land Brandenburg - Darstellung als Punktgeometrie (Point)",
    "description": "Der Datenbestand beinhaltet die Punktdaten zu den betriebenen Blockheizkraftwerken und Verbrennungsmotoranlagen im Land Brandenburg aus dem Anlageninformationssystem LIS-A.",
    "language": [ "ger" ],
    "spatial": 
        {"location": "none",
        "extent": "Landkreise Prignitz und Ostprignitz-Ruppin",
        "resolution": "vector"},
    "temporal": 
        {"reference_date": "2016-03-31",
        "start": "none",
        "end": "none",
        "resolution": "none"},
    "sources": [
        {"name": "Landwirtschafts- und Umweltinformationssystem des Landes Brandenburg (LUIS-BB) zum Thema Immissionsschutz / Klima. (03.01.2017)", "description": "Der Datenbestand beinhaltet die Punktdaten zu den betriebenen Blockheizkraftwerken und Verbrennungsmotoranlagen im Land Brandenburg aus dem Anlageninformationssystem LIS-A.", "url": "https://metaver.de/search/dls/#?serviceId=F92A0F18-7A1E-44E2-9F59-98968259F8F8&datasetId=69818B05-CDB6-420A-978D-CD0EF0C55AA6", "license": "Datenlizenz Deutschland - Namensnennung", "copyright": "© Landesbetrieb Geoinformation und Vermessung. Alle Rechte vorbehalten."},
        {"name": "Fachinformationssystem LIS-A", "description": "Datenbankauszug aus LIS-A im Excelformat", "url": "http://umwelt.landsh.server.de/servlet/is/114885/", "license": "", "copyright": ""},
        {"name": "Deutsche Gesellschaft für Sonnenenergie e.V. DGS", "description": "Energy Map - Daten zur durchschnittlichen jährlichen Stromproduktion und zur Stromproduktion 2013", "url": "http://www.energymap.info/download.html", "license": "", "copyright": ""}],
    "license": 
        {"id": "",
        "name": "Datenlizenz Deutschland - Namensnennung",
        "version": "2.0",
        "url": "https://www.govdata.de/dl-de/by-2-0; dl-de-by-2.0",
        "instruction": "Namensnennung: Landesamt für Umwelt Brandenburg, Angabe der URL der Datenquelle, Angabe der Datensatzbezeichnung",
        "copyright": "© Landesbetrieb Geoinformation und Vermessung. Alle Rechte vorbehalten."},
    "contributors": [
        {"name": "Anna Seefried", "email": "", "date": "2017-08-26", "comment": "Create metadata"},
        {"name": "", "email": "", "date": "", "comment": ""} ],
    "resources": [
        {"name": "supply.windnode_chpplant_brandenburg",
        "format": "PostgreSQL",
        "fields": [
            {"name": "Best_Nr", "description": "Betriebsstättennummer", "unit": ""},
            {"name": "Best_Name", "description": "Betriebsbezeichnung", "unit": ""},
            {"name": "Ort", "description": "Angabe Ort", "unit": ""},
            {"name": "Ortsteil", "description": "Angabe Ortsteil", "unit": ""},
            {"name": "Anl_Nr", "description": "Anlagennnummer", "unit": ""},
            {"name": "Anl_Bez", "description": "Bezeichnung der Anlage", "unit": ""},
            {"name": "Nr_4BV", "description": "Nummer Anhang 4. BImSchV", "unit": ""},
            {"name": "AnlArt_4BV", "description": "Anlagenart Anhang 4. BImSchV", "unit": ""},
            {"name": "Ostwert", "description": "Ostwert (ETRS89 /UTM Zone 33N 7-stellig)", "unit": ""},
            {"name": "Nordwert", "description": "Nordwert (ETRS89/ UTM Zone 33N 7-stellig)", "unit": ""},
            {"name": "Inbetriebn", "description": "Datum Inbetriebnahme", "unit": ""},
            {"name": "Alt_an_anz", "description": "Altanlagenanzeige", "unit": ""},
            {"name": "Leistung", "description": "", "unit": ""},
            {"name": "Einheit", "description": "Maßeinheit der Leistung/ Kapazität", "unit": ""},
            {"name": "Bezug", "description": "", "unit": "Bezugsgröße der Leistung/ Kapazität"},
            {"name": "gid", "description": "", "unit": ""},
            {"name": "ade", "description": "", "unit": ""},
            {"name": "gf", "description": "", "unit": ""},
            {"name": "bsg", "description": "", "unit": ""},
            {"name": "rs", "description": "", "unit": ""},
            {"name": "ags", "description": "", "unit": ""},
            {"name": "sdv_rs", "description": "", "unit": ""},
            {"name": "gen", "description": "", "unit": ""},
            {"name": "bez", "description": "", "unit": ""},
            {"name": "ibz", "description": "", "unit": ""},
            {"name": "bem", "description": "", "unit": ""},
            {"name": "nbd", "description": "", "unit": ""},
            {"name": "sn_l", "description": "", "unit": ""},
            {"name": "sn_r", "description": "", "unit": ""},
            {"name": "sn_k", "description": "", "unit": ""},
            {"name": "rs", "description": "", "unit": ""},
            {"name": "sn_v1", "description": "", "unit": ""},
            {"name": "sn_v2", "description": "", "unit": ""},
            {"name": "sn_g", "description": "", "unit": ""},
            {"name": "fk_s3", "description": "", "unit": ""},
            {"name": "nuts", "description": "", "unit": ""},
            {"name": "rs_0", "description": "", "unit": ""},
            {"name": "ags_0", "description": "", "unit": ""},
            {"name": "wsk", "description": "", "unit": ""},
            {"name": "debkg_id", "description": "", "unit": ""},
            {"name": "abgleich_e", "description": "Angleich ob in der ego_dp-Datenbank vorhanden, fehlt bedeutet nein", "unit": ""},
            {"name": "el_kw", "description": "Elektrische Leistung", "unit": "kW"},
            {"name": "kwh_average", "description": "Durchscnittliche Stromproduktion", "unit": "kwh"}]}],
    "metadata_version": "1.3"}';

-- select description
SELECT obj_description('supply.lfu_chpplant_prignitz' ::regclass) ::json;
